pipeline {
  agent any

tools {
    nodejs "Nodejs"
}

 environment {
    DOCKER_REGISTRY = "docker.io"
    DOCKERHUB_CREDENTIALS = credentials('DOCKER_HUB_CREDENTIALS')
    VERSION = "${env.BUILD_ID}"
  }

  stages {

 stage('Install Dependencies') {
      steps {

        sh 'npm ci'
      }
    }

    stage('Build Project') {
      steps {
        // Build the Angular project
        sh 'npm run build'
      }
    }


     stage('Docker Build and Push') {
                 steps {
                     withCredentials([usernamePassword(credentialsId: 'DOCKER_HUB_CREDENTIALS', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                         sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                         dir('Restaurant-Listing') {
                             sh 'docker build -t raghuuppar/frontend:${VERSION} .'
                             sh 'docker push raghuuppar/frontend:${VERSION}'
                         }
                     }
                 }
             }


     stage('Cleanup Workspace') {
      steps {
        deleteDir()
      }
    }

     stage('Update Image Tag in GitOps') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
            sh '''
                # Configure Git
                git config --global user.email "raghavendruppar@gmail.com"
                git config --global user.name "raghavendru"

                # Clone using HTTPS with token
                git clone "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/raghvendru/Restaurant-Service.git"
                cd Restaurant-Service

                # Update manifest
                sed -i "s|image:.*|image: raghuuppar/frontend:${VERSION}|" deployment-folder/aws/angular-manifest.yml

                # Push changes
                git add deployment-folder/aws/angular-manifest.yml
                git commit -m "Update image tag for version ${VERSION}"
                git push origin main
            '''
        }
    }
}
  }

}

